---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1km2hmm9d0ewsdgtjqhundhlkultnyx560smkq9ut42ura0npyvtqfwtz0w
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1km2hmm9d0ewsdgtjqhundhlkultnyx560smkq9ut42ura0npyvtqfwtz0w
