# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:YaUvCesR1DBSfw==,iv:32UzGGffAiF5/MUfUSxD+ydvD8b3MJgVa3FHGrUT0og=,tag:YOz5nzQ78fCCFTUbyL+tMA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9PHANKsrehx4d/cYxPmFOPDaHjlX,iv:pOfMiBcC2bbxIiODgsy8iRAyDQI8s0ILpLjGJ7Kx1is=,tag:4I6Rjsc3pVxUd5z2iracYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1km2hmm9d0ewsdgtjqhundhlkultnyx560smkq9ut42ura0npyvtqfwtz0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTHgrT3oxUzN2MXIvTmRw
            VGUzcW1YRG5XMzJPajVxM0hIaEo5SjNQNXdJCmtnQ21WSk9CQnJ5TTZ0cFVHYjVE
            YjJyNDRhZUMxZ0l5dlhCQUtlZmVQbU0KLS0tIDV2SmhIaHd6cHVzc0daN3BGQ1Z3
            bUh2cVRVd0NmUm1NcktvSkNUL3VSM1EKptLxywHhSsk1wst2sYKxhEMZsU4PZuzf
            ioVwyeO2p4ijlXbKIkL9brYx8lWFdgs4Dsq1TwIK1oZHV001htkQyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-03T20:31:32Z"
    mac: ENC[AES256_GCM,data:lP81KnsP+cw7UHrcEzkcfCNJ+Vs8b4op0CJ9VSBY6TdYyFBKlUZ4/sIYuzhOHKXqD6TJPf4PLEh1kl2fK4txC2T+v1+qjjP5s6nyhRlMLhTimG3vh9jwB6KwSHP3C1BfZgX6q2sNACCSh4ts0yw81wJ4mPEGnSGmGR0FKCshRp8=,iv:G4vBKc1x8o59+5pVnnqL0SLy0es4iDPMZAvMOvmBN7w=,tag:k7XeBTrn5U4nnB3zqS4DfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
