---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/London
  METALLB_LB_RANGE: 159.69.212.175
  METALLB_K8S_GATEWAY_ADDR: 159.69.212.175
  METALLB_TRAEFIK_ADDR: 159.69.212.175
